### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by Pierre-Demessence**
Let's review the app and be sure it's ready for 1.0.

Please everyone run the app and play a lot with it, and if you think everything is fine then approve this PR !

### CODE REVIEW

**Review by FaizanDurrani — DISMISSED** [review]
Hole visuals are weird on Android Pie (9.0)

**Review by camblomquist — DISMISSED** [review]
We're hitting the target frame rate and everything else seems to be working.

**Comment by Pierre-Demessence** [comment]
I approve of it (can't approve my own PR 😄 )

**Review by camblomquist — DISMISSED** [review]

**Review by conorlawton — DISMISSED** [review]
Looks good, feels good 👍

**Review by camblomquist — APPROVED** [review]
We gucci

**Review by FaizanDurrani — APPROVED** [review]

**Review by conorlawton — APPROVED** [review]

**Pull request merged**
